/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScooterverhuurRouteImport } from './routes/scooterverhuur'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as EetcafeRouteImport } from './routes/eetcafe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvenementenIndexRouteImport } from './routes/evenementen/index'
import { Route as EvenementenVergaderzaalRouteImport } from './routes/evenementen/vergaderzaal'
import { Route as EvenementenUitvaartRouteImport } from './routes/evenementen/uitvaart'
import { Route as EvenementenFeestzaalRouteImport } from './routes/evenementen/feestzaal'
import { Route as EvenementenCateringRouteImport } from './routes/evenementen/catering'
import { Route as EvenementenBruiloftRouteImport } from './routes/evenementen/bruiloft'
import { Route as EvenementenBinnentuinRouteImport } from './routes/evenementen/binnentuin'

const ScooterverhuurRoute = ScooterverhuurRouteImport.update({
  id: '/scooterverhuur',
  path: '/scooterverhuur',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const EetcafeRoute = EetcafeRouteImport.update({
  id: '/eetcafe',
  path: '/eetcafe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenIndexRoute = EvenementenIndexRouteImport.update({
  id: '/evenementen/',
  path: '/evenementen/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenVergaderzaalRoute = EvenementenVergaderzaalRouteImport.update({
  id: '/evenementen/vergaderzaal',
  path: '/evenementen/vergaderzaal',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenUitvaartRoute = EvenementenUitvaartRouteImport.update({
  id: '/evenementen/uitvaart',
  path: '/evenementen/uitvaart',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenFeestzaalRoute = EvenementenFeestzaalRouteImport.update({
  id: '/evenementen/feestzaal',
  path: '/evenementen/feestzaal',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenCateringRoute = EvenementenCateringRouteImport.update({
  id: '/evenementen/catering',
  path: '/evenementen/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenBruiloftRoute = EvenementenBruiloftRouteImport.update({
  id: '/evenementen/bruiloft',
  path: '/evenementen/bruiloft',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenBinnentuinRoute = EvenementenBinnentuinRouteImport.update({
  id: '/evenementen/binnentuin',
  path: '/evenementen/binnentuin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/eetcafe': typeof EetcafeRoute
  '/hotel': typeof HotelRoute
  '/over-ons': typeof OverOnsRoute
  '/restaurant': typeof RestaurantRoute
  '/scooterverhuur': typeof ScooterverhuurRoute
  '/evenementen/binnentuin': typeof EvenementenBinnentuinRoute
  '/evenementen/bruiloft': typeof EvenementenBruiloftRoute
  '/evenementen/catering': typeof EvenementenCateringRoute
  '/evenementen/feestzaal': typeof EvenementenFeestzaalRoute
  '/evenementen/uitvaart': typeof EvenementenUitvaartRoute
  '/evenementen/vergaderzaal': typeof EvenementenVergaderzaalRoute
  '/evenementen': typeof EvenementenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/eetcafe': typeof EetcafeRoute
  '/hotel': typeof HotelRoute
  '/over-ons': typeof OverOnsRoute
  '/restaurant': typeof RestaurantRoute
  '/scooterverhuur': typeof ScooterverhuurRoute
  '/evenementen/binnentuin': typeof EvenementenBinnentuinRoute
  '/evenementen/bruiloft': typeof EvenementenBruiloftRoute
  '/evenementen/catering': typeof EvenementenCateringRoute
  '/evenementen/feestzaal': typeof EvenementenFeestzaalRoute
  '/evenementen/uitvaart': typeof EvenementenUitvaartRoute
  '/evenementen/vergaderzaal': typeof EvenementenVergaderzaalRoute
  '/evenementen': typeof EvenementenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/eetcafe': typeof EetcafeRoute
  '/hotel': typeof HotelRoute
  '/over-ons': typeof OverOnsRoute
  '/restaurant': typeof RestaurantRoute
  '/scooterverhuur': typeof ScooterverhuurRoute
  '/evenementen/binnentuin': typeof EvenementenBinnentuinRoute
  '/evenementen/bruiloft': typeof EvenementenBruiloftRoute
  '/evenementen/catering': typeof EvenementenCateringRoute
  '/evenementen/feestzaal': typeof EvenementenFeestzaalRoute
  '/evenementen/uitvaart': typeof EvenementenUitvaartRoute
  '/evenementen/vergaderzaal': typeof EvenementenVergaderzaalRoute
  '/evenementen/': typeof EvenementenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/eetcafe'
    | '/hotel'
    | '/over-ons'
    | '/restaurant'
    | '/scooterverhuur'
    | '/evenementen/binnentuin'
    | '/evenementen/bruiloft'
    | '/evenementen/catering'
    | '/evenementen/feestzaal'
    | '/evenementen/uitvaart'
    | '/evenementen/vergaderzaal'
    | '/evenementen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/eetcafe'
    | '/hotel'
    | '/over-ons'
    | '/restaurant'
    | '/scooterverhuur'
    | '/evenementen/binnentuin'
    | '/evenementen/bruiloft'
    | '/evenementen/catering'
    | '/evenementen/feestzaal'
    | '/evenementen/uitvaart'
    | '/evenementen/vergaderzaal'
    | '/evenementen'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/eetcafe'
    | '/hotel'
    | '/over-ons'
    | '/restaurant'
    | '/scooterverhuur'
    | '/evenementen/binnentuin'
    | '/evenementen/bruiloft'
    | '/evenementen/catering'
    | '/evenementen/feestzaal'
    | '/evenementen/uitvaart'
    | '/evenementen/vergaderzaal'
    | '/evenementen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  EetcafeRoute: typeof EetcafeRoute
  HotelRoute: typeof HotelRoute
  OverOnsRoute: typeof OverOnsRoute
  RestaurantRoute: typeof RestaurantRoute
  ScooterverhuurRoute: typeof ScooterverhuurRoute
  EvenementenBinnentuinRoute: typeof EvenementenBinnentuinRoute
  EvenementenBruiloftRoute: typeof EvenementenBruiloftRoute
  EvenementenCateringRoute: typeof EvenementenCateringRoute
  EvenementenFeestzaalRoute: typeof EvenementenFeestzaalRoute
  EvenementenUitvaartRoute: typeof EvenementenUitvaartRoute
  EvenementenVergaderzaalRoute: typeof EvenementenVergaderzaalRoute
  EvenementenIndexRoute: typeof EvenementenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scooterverhuur': {
      id: '/scooterverhuur'
      path: '/scooterverhuur'
      fullPath: '/scooterverhuur'
      preLoaderRoute: typeof ScooterverhuurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eetcafe': {
      id: '/eetcafe'
      path: '/eetcafe'
      fullPath: '/eetcafe'
      preLoaderRoute: typeof EetcafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/': {
      id: '/evenementen/'
      path: '/evenementen'
      fullPath: '/evenementen'
      preLoaderRoute: typeof EvenementenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/vergaderzaal': {
      id: '/evenementen/vergaderzaal'
      path: '/evenementen/vergaderzaal'
      fullPath: '/evenementen/vergaderzaal'
      preLoaderRoute: typeof EvenementenVergaderzaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/uitvaart': {
      id: '/evenementen/uitvaart'
      path: '/evenementen/uitvaart'
      fullPath: '/evenementen/uitvaart'
      preLoaderRoute: typeof EvenementenUitvaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/feestzaal': {
      id: '/evenementen/feestzaal'
      path: '/evenementen/feestzaal'
      fullPath: '/evenementen/feestzaal'
      preLoaderRoute: typeof EvenementenFeestzaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/catering': {
      id: '/evenementen/catering'
      path: '/evenementen/catering'
      fullPath: '/evenementen/catering'
      preLoaderRoute: typeof EvenementenCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/bruiloft': {
      id: '/evenementen/bruiloft'
      path: '/evenementen/bruiloft'
      fullPath: '/evenementen/bruiloft'
      preLoaderRoute: typeof EvenementenBruiloftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/binnentuin': {
      id: '/evenementen/binnentuin'
      path: '/evenementen/binnentuin'
      fullPath: '/evenementen/binnentuin'
      preLoaderRoute: typeof EvenementenBinnentuinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  EetcafeRoute: EetcafeRoute,
  HotelRoute: HotelRoute,
  OverOnsRoute: OverOnsRoute,
  RestaurantRoute: RestaurantRoute,
  ScooterverhuurRoute: ScooterverhuurRoute,
  EvenementenBinnentuinRoute: EvenementenBinnentuinRoute,
  EvenementenBruiloftRoute: EvenementenBruiloftRoute,
  EvenementenCateringRoute: EvenementenCateringRoute,
  EvenementenFeestzaalRoute: EvenementenFeestzaalRoute,
  EvenementenUitvaartRoute: EvenementenUitvaartRoute,
  EvenementenVergaderzaalRoute: EvenementenVergaderzaalRoute,
  EvenementenIndexRoute: EvenementenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
